# Generated by Django 4.1.2 on 2022-11-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_name', models.CharField(db_index=True, max_length=25, verbose_name='Имя')),
                ('content', models.TextField(verbose_name='Описание')),
                ('grade', models.CharField(max_length=25, verbose_name='Категория барбера')),
                ('clients_count', models.IntegerField(default=0, verbose_name='Всего клиентов')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Барбер',
                'verbose_name_plural': 'Барберы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=25, verbose_name='Имя')),
                ('visits_count', models.IntegerField(default=0, verbose_name='Число посещений')),
                ('phone', models.IntegerField(null=True, verbose_name='Номер телефона')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(null=True, verbose_name='Дата и время визита')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='browser.barber', verbose_name='Имя барбера')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='browser.client', verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Посещение клиента',
                'verbose_name_plural': 'Посещения клиентов',
                'ordering': ['id'],
            },
        ),
    ]
